services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: robocook_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge_bases
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
  ollama:
      image: ollama/ollama:latest
      container_name: ollama
      restart: unless-stopped
      ports:
        - "11434:11434"
      volumes:
        - ollama_data:/root/.ollama
      environment:
        - OLLAMA_HOST=0.0.0.0
      entrypoint: >
        sh -c "
          ollama serve & 
          sleep 5 && 
          ollama pull llama3.2:3b-instruct-q4_0 && 
          wait"

  robocook_app:
    build:
      context: .
      dockerfile: recipe_generation/Dockerfile.robocook
    container_name: robocook_main
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - postgres
      - ollama
    tty: true          
    stdin_open: true   

volumes:
  pgdata:
  ollama_data: